import fs from 'fs'
import path from 'path'

export const AUDIO_DIR = path.join(process.cwd(), 'audio')

export type AudioVoice = 'yunus' | 'mert' | 'lisa' | 'gulsu'
export type AudioCategory = 'universal' | 'restoran' | 'guzellik' | 'saglik' | 'kuafor'

export const MULTILANG_LANGS = ['ar', 'da', 'es', 'ru'] as const
export type MultilangLang = typeof MULTILANG_LANGS[number]

const MULTILANG_SENTENCES: Record<MultilangLang, Record<AudioCategory, Array<[string, string]>>> = {
  ar: {
    universal: [
      ['merhaba_1','مرحباً، أهلاً وسهلاً! كيف يمكنني مساعدتك؟'],
      ['merhaba_2','مرحباً! كيف يمكنني مساعدتك اليوم؟'],
      ['merhaba_3','مساء الخير! يسعدنا وجودك معنا.'],
      ['merhaba_4','مرحباً، أنا مساعدك الرقمي. كيف يمكنني مساعدتك؟'],
      ['merhaba_5','أهلاً وسهلاً! أنت في المكان الصحيح للحجز.'],
      ['tarih_sor','في أي تاريخ تريد حجز موعد؟'],
      ['saat_sor','ما هو توقيتك المفضل؟'],
      ['isim_sor','هل يمكنني معرفة اسمك الأول والأخير؟'],
      ['telefon_sor','هل يمكنني الحصول على رقم هاتفك؟'],
      ['email_sor','هل يمكنك مشاركة بريدك الإلكتروني؟'],
      ['kisi_sor','لكم شخص تريد الحجز؟'],
      ['ozel_istek','هل لديك أي طلب خاص؟'],
      ['ilk_ziyaret','هل سبق أن زرتنا من قبل؟'],
      ['onay_1','تم إنشاء حجزك بنجاح.'],
      ['onay_2','تم تأكيد موعدك، في انتظارك.'],
      ['onay_3','رائع! كل شيء على ما يرام، إلى اللقاء.'],
      ['onay_bildirim','أرسلنا تفاصيل حجزك عبر الرسائل القصيرة والبريد الإلكتروني.'],
      ['teyit_sor','لتأكيد موعدك، يرجى قول نعم أو الضغط على المفتاح رقم واحد.'],
      ['tekrar','هل فهمت المعلومات بشكل صحيح؟ دعني أكررها مرة أخرى.'],
      ['iptal_1','أفهم أنك تريد إلغاء حجزك.'],
      ['iptal_2','تم إلغاء حجزك. نأمل في رؤيتك مجدداً.'],
      ['degisiklik_sor','هل تريد تغيير موعدك؟'],
      ['yeni_tarih','ما هو تاريخك الجديد المفضل؟'],
      ['degisiklik_onay','تم حفظ التغيير الخاص بك.'],
      ['dolu_1','آسف، الوقت الذي اخترته محجوز. هل يمكننا تجربة وقت آخر؟'],
      ['dolu_2','للأسف، لا توجد أماكن متاحة في هذا التاريخ.'],
      ['hata_1','حدثت مشكلة، هل يمكنك المحاولة مرة أخرى؟'],
      ['anlayamadim','لم أتمكن من التحقق من المعلومات التي أدخلتها، هل يمكنك تكرارها؟'],
      ['ses_yok','لم أفهمك بشكل صحيح، هل يمكنك التحدث بصوت أعلى قليلاً؟'],
      ['hatirlatma_1','اتصلنا بك بشأن موعدك غداً، يوماً سعيداً.'],
      ['hatirlatma_2','تبقت ساعتان على موعدك، في انتظارك.'],
      ['hatirlatma_iptal','إذا أردت إلغاء موعدك، يمكنك الاتصال بنا.'],
      ['veda_1','شكراً لك، نتمنى لك يوماً سعيداً.'],
      ['veda_2','إلى اللقاء، اعتنِ بنفسك.'],
      ['veda_3','شكراً لاختيارك لنا.'],
      ['veda_4','يوماً سعيداً، وداعاً.'],
      ['baska_yardim','هل يمكنني مساعدتك في شيء آخر؟'],
      ['veda_kisa','إلى اللقاء!'],
    ],
    restoran: [
      ['merhaba_1','مرحباً، أنت في المكان المثالي لتجربة لذيذة!'],
      ['merhaba_2','أهلاً وسهلاً! يسعدني مساعدتك في حجز طاولة.'],
      ['merhaba_3','مرحباً! هل تحتفل بيوم خاص، أم تخطط لتناول وجبة ممتعة؟'],
      ['kisi_sor','لكم شخص تريد حجز طاولة؟'],
      ['mekan_sor','هل تفضل الجلوس في الداخل أم في الخارج؟'],
      ['sigara_sor','هل تريد الجلوس في منطقة التدخين أم غير التدخين؟'],
      ['ozel_gun','هل هناك عيد ميلاد أو احتفال خاص؟'],
      ['diyet','لدينا خيارات نباتية وخيارات صارمة، هل تريد الإشارة إلى ذلك؟'],
      ['alerji','هل لديك أي حساسية من بعض الأطعمة؟'],
      ['cocuk','هل تريد كرسي أطفال أو قائمة طعام للأطفال؟'],
      ['pencere','هل تريد طاولة بجانب النافذة؟'],
      ['dekor','هل تريد منا تحضير ديكور خاص أو ورود؟'],
      ['mutfak_bilgi','تتألف مطبخنا من المأكولات التركية والمتوسطية.'],
      ['menu_bilgi','لمعرفة قائمة الطعام اليومية الخاصة، يرجى زيارة موقعنا الإلكتروني.'],
      ['kahvalti','يُقدَّم الفطور البوفيه المفتوح في عطلات نهاية الأسبوع.'],
      ['otopark','لدينا خدمة مواقف مجانية.'],
      ['vale','يمكنك الاستفادة من خدمة صف السيارات.'],
      ['onay_1','تم تحضير طاولتك، بالهناء والشفاء!'],
      ['onay_2','تم استلام حجزك، نتمنى لك وجبة شهية.'],
      ['onay_3','سيكون من دواعي سرورنا استقبالك على أفضل طاولة.'],
      ['gec_kalma','إذا تأخرت، يرجى الاتصال بنا، سنحتفظ بطاولتك لمدة خمس عشرة دقيقة.'],
    ],
    guzellik: [
      ['merhaba_1','مرحباً، أنت في المكان المثالي لتدليل نفسك!'],
      ['merhaba_2','أهلاً وسهلاً! نحن هنا من أجل تجربة استرخاء مريحة.'],
      ['merhaba_3','مرحباً، أنت تخصص وقتاً خاصاً لنفسك اليوم، خيار رائع!'],
      ['hizmet_sor','بأي خدمة من خدماتنا تريد الاستفادة؟'],
      ['hizmet_liste','لدينا خيارات التدليك وعناية البشرة وعناية الجسم.'],
      ['amac_sor','هل تفضل الاسترخاء أم التنقية أم التنشيط؟'],
      ['sure_sor','لنحدد مدة جلستك: خمسون دقيقة أم ثمانون دقيقة؟'],
      ['cift_sor','هل تفضل جلسة ثنائية أم فردية؟'],
      ['cilt_tipi','هل يمكنك إخبارنا عن نوع بشرتك؟'],
      ['alerji','هل لديك أي حساسية أو تحسس؟'],
      ['hamile','هل أنتِ حامل؟ نحتاج إلى معرفة ذلك لبعض خدماتنا.'],
      ['terapist_sor','هل لديك تفضيل لمعالج معين؟'],
      ['aromaterapi','هل تفضل العلاج بالروائح؟'],
      ['sicak_tas','هل تريد إضافة تدليك الحجارة الساخنة؟'],
      ['erken_gel','ننصحك بالحضور قبل عشر دقائق من موعد جلستك.'],
      ['havlu','خدمة المناشف والنعال مجانية.'],
      ['su','ننصحك بشرب الماء، وسيُقدَّم لك الماء بعد الجلسة.'],
      ['onay_1','موعدك جاهز، ستشعر بتحسن رائع!'],
      ['onay_2','تم تأكيد جلستك. استعد للاسترخاء!'],
      ['onay_3','في انتظارك، ونحن متأكدون أنك ستمر بتجربة رائعة.'],
    ],
    saglik: [
      ['merhaba_1','مرحباً، شكراً لاتصالك بعيادتنا.'],
      ['merhaba_2','أهلاً وسهلاً، لقد اتخذت الخطوة الصحيحة لصحتك.'],
      ['merhaba_3','مرحباً، أنت تتحدث مع مركز المواعيد لدينا.'],
      ['uzman_sor','في أي تخصص تريد حجز موعد؟'],
      ['kayit_sor','هل سبق أن زرت عيادتنا من قبل؟'],
      ['tc_sor','هل يمكنني الحصول على رقم هويتك الوطنية؟'],
      ['sigorta_sor','هل يمكنك مشاركة معلومات التأمين الخاصة بك؟'],
      ['sgk_sor','هل تريد استخدام التأمين الصحي الحكومي أم التأمين الخاص؟'],
      ['sikayet_sor','هل يمكنك وصف شكواك باختصار؟'],
      ['kronik','هل لديك مرض مزمن أو علاج جارٍ؟'],
      ['ilac_sor','هل تتناول أي أدوية؟'],
      ['acil_sor','هل تفضل موعداً عاجلاً أم موعداً عادياً؟'],
      ['terapi_turu','هل تفضل العلاج الفردي، علاج الأزواج، أم علاج الأسرة؟'],
      ['online_seans','لدينا أيضاً إمكانية إجراء جلسات عبر الإنترنت.'],
      ['gizlilik','معلومات جلستك محفوظة بسرية تامة.'],
      ['ilk_seans','الجلسة الأولى هي جلسة تقييم، وسيستغرق موعدك ستين دقيقة.'],
      ['dis_tur','هل تريد فحصاً، علاجاً، أم تطبيقاً تجميلياً؟'],
      ['dis_agri','هل تعاني من آلام في الأسنان؟'],
      ['onay_1','تم إنشاء موعدك، نتمنى لك أياماً صحية.'],
      ['onay_2','سينتظرك طبيبك في الوقت المحدد.'],
      ['iptal_bilgi','لإلغاء الموعد، يرجى الاتصال بنا قبل أربع وعشرين ساعة.'],
      ['belgeler','نرجو أن تحضر بطاقة هويتك وبطاقة التأمين معك.'],
      ['ac_karin','يجب أن تأتي على معدة فارغة.'],
    ],
    kuafor: [
      ['merhaba_1','مرحباً! أنت في المكان المثالي للحصول على مظهر رائع.'],
      ['merhaba_2','أهلاً وسهلاً، شكراً لثقتك بنا في شعرك.'],
      ['merhaba_3','مرحباً، نحن هنا من أجل إطلالة جديدة!'],
      ['hizmet_sor','أي خدمة من خدماتنا تريد؟'],
      ['islem_sor','هل تريد قص الشعر، التلوين، أم العناية؟'],
      ['stilist_sor','هل لديك تفضيل لمصفف معين؟'],
      ['sac_tipi','ما هو طول شعرك ونوعه؟'],
      ['kimyasal','هل سبق أن أجريت معالجة كيميائية لشعرك؟'],
      ['renk_sor','ما درجة اللون الذي تفكر فيه؟'],
      ['referans','هل لديك صورة مرجعية؟'],
      ['teknik_sor','هل تريد بالياج، أومبري، أم لون واحد؟'],
      ['berber_islem','قص الشعر، حلاقة اللحية، أم الاثنين معاً؟'],
      ['sakal_sor','هل تريد قص لحيتك أم تشكيلها؟'],
      ['ustura','هل تريد حلاقة الموسى الكلاسيكية؟'],
      ['maske','هل تريد إضافة قناع عناية بالشعر؟'],
      ['kas','هل تريد الاستفادة من خدمة إزالة الحواجب لدينا؟'],
      ['onay_1','تم استلام موعدك، استعد للمظهر الأنيق!'],
      ['onay_2','سينتظرك مصففك في الوقت المحدد.'],
      ['onay_3','تم تأكيد حجزك، نتمنى لك تجربة رائعة.'],
      ['bilgi_1','لا حاجة لغسل شعرك قبل موعدك.'],
    ],
  },
  da: {
    universal: [
      ['merhaba_1','Hej, velkommen! Hvordan kan jeg hjælpe dig?'],
      ['merhaba_2','Hej! Hvordan kan jeg hjælpe dig i dag?'],
      ['merhaba_3','God dag! Vi er glade for at se dig her.'],
      ['merhaba_4','Hej, jeg er din digitale assistent. Hvordan kan jeg hjælpe dig?'],
      ['merhaba_5','Velkommen! Du er det rette sted for at foretage en reservation.'],
      ['tarih_sor','Hvilken dato ønsker du at bestille en tid?'],
      ['saat_sor','Hvad er dit foretrukne tidspunkt?'],
      ['isim_sor','Må jeg spørge om dit fornavn og efternavn?'],
      ['telefon_sor','Må jeg få dit telefonnummer?'],
      ['email_sor','Vil du dele din e-mailadresse?'],
      ['kisi_sor','Hvor mange personer vil du reservere til?'],
      ['ozel_istek','Har du nogen særlige ønsker?'],
      ['ilk_ziyaret','Har du besøgt os før?'],
      ['onay_1','Din reservation er blevet oprettet.'],
      ['onay_2','Din aftale er bekræftet, vi ser frem til at se dig.'],
      ['onay_3','Fantastisk! Alt er i orden, vi ses.'],
      ['onay_bildirim','Vi har sendt dine reservationsoplysninger via SMS og e-mail.'],
      ['teyit_sor','For at bekræfte din aftale, svar venligst Ja eller tryk på tasten et.'],
      ['tekrar','Har jeg forstået oplysningerne korrekt? Lad mig gentage dem endnu en gang.'],
      ['iptal_1','Jeg forstår, at du ønsker at annullere din reservation.'],
      ['iptal_2','Din reservation er annulleret. Vi håber at se dig igen.'],
      ['degisiklik_sor','Ønsker du at ændre din aftale?'],
      ['yeni_tarih','Hvad er din nye foretrukne dato?'],
      ['degisiklik_onay','Din ændring er gemt.'],
      ['dolu_1','Undskyld, det valgte tidspunkt er optaget. Kan vi prøve et andet tidspunkt?'],
      ['dolu_2','Desværre er der ingen ledige pladser på denne dato.'],
      ['hata_1','Der opstod et problem, vil du prøve igen?'],
      ['anlayamadim','Jeg kunne ikke verificere de oplysninger, du har angivet. Kan du sige det igen?'],
      ['ses_yok','Jeg forstod dig ikke korrekt, kan du sige det lidt højere?'],
      ['hatirlatma_1','Vi ringede til dig angående din aftale i morgen, god dag.'],
      ['hatirlatma_2','Der er to timer til din aftale, vi venter på dig.'],
      ['hatirlatma_iptal','Hvis du ønsker at aflyse din aftale, er du velkommen til at ringe til os.'],
      ['veda_1','Tak, vi ønsker dig en god dag.'],
      ['veda_2','Vi ses, pas godt på dig selv.'],
      ['veda_3','Tak fordi du valgte os.'],
      ['veda_4','God dag, farvel.'],
      ['baska_yardim','Kan jeg hjælpe dig med noget andet?'],
      ['veda_kisa','Vi ses!'],
    ],
    restoran: [
      ['merhaba_1','Hej, du er det rette sted for en lækker oplevelse!'],
      ['merhaba_2','Velkommen! Jeg hjælper dig gerne med at reservere et bord.'],
      ['merhaba_3','Hej! Fejrer du en særlig dag, eller planlægger du bare et hyggeligt måltid?'],
      ['kisi_sor','Hvor mange personer vil du reservere et bord til?'],
      ['mekan_sor','Foretrækker du indendørs eller udendørs?'],
      ['sigara_sor','Ønsker du at sidde i ryger- eller ikke-rygerafdelingen?'],
      ['ozel_gun','Er der en fødselsdag eller en særlig fejring?'],
      ['diyet','Vi har vegetariske og veganske muligheder på menuen, vil du nævne det?'],
      ['alerji','Er der nogen fødevarer, du er allergisk over for?'],
      ['cocuk','Ønsker du en babystol eller en børnemenu?'],
      ['pencere','Ønsker du et bord ved vinduet?'],
      ['dekor','Ønsker du, at vi forbereder særlig dekoration eller blomster?'],
      ['mutfak_bilgi','Vores køkken består af tyrkisk og middelhavsmad.'],
      ['menu_bilgi','For vores daglige specialmenu, besøg venligst vores hjemmeside.'],
      ['kahvalti','Vores buffetmorgenmad serveres i weekenderne.'],
      ['otopark','Vi tilbyder gratis parkering.'],
      ['vale','Du kan benytte vores valetservice.'],
      ['onay_1','Dit bord er klar, velbekomme!'],
      ['onay_2','Din reservation er modtaget, vi ønsker dig et lækkert måltid.'],
      ['onay_3','Vi ser frem til at byde dig velkommen ved det smukkeste bord.'],
      ['gec_kalma','Hvis du er forsinket, ring venligst til os, vi gemmer dit bord i femten minutter.'],
    ],
    guzellik: [
      ['merhaba_1','Hej, du er det rette sted for at forkæle dig selv!'],
      ['merhaba_2','Velkommen! Vi er her for at give dig en afslappende oplevelse.'],
      ['merhaba_3','Hej, du tager dig tid til dig selv i dag, et fantastisk valg!'],
      ['hizmet_sor','Hvilken af vores tjenester ønsker du at benytte?'],
      ['hizmet_liste','Vi tilbyder massage, hudpleje eller kropspleje.'],
      ['amac_sor','Foretrækker du afslapning, rensning eller genoplivning?'],
      ['sure_sor','Lad os fastlægge din sessionslængde: halvtreds minutter eller firs minutter?'],
      ['cift_sor','Foretrækker du en par- eller enkelt session?'],
      ['cilt_tipi','Kan du fortælle os om din hudtype?'],
      ['alerji','Har du nogen allergier eller følsomheder?'],
      ['hamile','Er du gravid? Vi har brug for at vide det til nogle af vores tjenester.'],
      ['terapist_sor','Har du en præference for en bestemt terapeut?'],
      ['aromaterapi','Foretrækker du aromaterapi?'],
      ['sicak_tas','Ønsker du at tilføje varmestens massage?'],
      ['erken_gel','Vi anbefaler, at du ankommer ti minutter før din session.'],
      ['havlu','Håndklæde- og tøffelservice er gratis.'],
      ['su','Vi anbefaler at drikke vand, der vil blive serveret vand efter din session.'],
      ['onay_1','Din aftale er klar, du vil føle dig fantastisk!'],
      ['onay_2','Din session er bekræftet. Gør dig klar til at slappe af!'],
      ['onay_3','Vi venter på dig, vi er sikre på, at du vil have en dejlig oplevelse.'],
    ],
    saglik: [
      ['merhaba_1','Hej, tak fordi du ringede til vores klinik.'],
      ['merhaba_2','Velkommen, du har taget det rigtige skridt for dit helbred.'],
      ['merhaba_3','Hej, du taler med vores aftalecentral.'],
      ['uzman_sor','Hvilken specialitet ønsker du at bestille en tid hos?'],
      ['kayit_sor','Har du besøgt vores klinik før?'],
      ['tc_sor','Må jeg bede om dit CPR-nummer?'],
      ['sigorta_sor','Vil du dele dine forsikringsoplysninger?'],
      ['sgk_sor','Ønsker du at bruge offentlig sygesikring eller privat forsikring?'],
      ['sikayet_sor','Kan du kortfattet beskrive dit problem?'],
      ['kronik','Har du en kronisk sygdom eller et igangværende behandlingsforløb?'],
      ['ilac_sor','Er der nogen medicin, du tager?'],
      ['acil_sor','Foretrækker du en akuttime eller en normal aftale?'],
      ['terapi_turu','Foretrækker du individuel terapi, parterapi eller familieterapi?'],
      ['online_seans','Vi tilbyder også mulighed for online sessioner.'],
      ['gizlilik','Dine sessionsoplysninger opbevares helt fortroligt.'],
      ['ilk_seans','Den første session er en vurderingssession, din aftale vil vare tres minutter.'],
      ['dis_tur','Ønsker du en kontrol, behandling eller æstetisk procedure?'],
      ['dis_agri','Har du tandpine?'],
      ['onay_1','Din aftale er oprettet, vi ønsker dig sunde dage.'],
      ['onay_2','Din læge vil vente på dig på det aftalte tidspunkt.'],
      ['iptal_bilgi','For at aflyse din aftale, ring venligst til os fireogtyve timer i forvejen.'],
      ['belgeler','Vi beder dig om at medbringe dit ID og forsikringskort.'],
      ['ac_karin','Du skal komme fastende.'],
    ],
    kuafor: [
      ['merhaba_1','Hej! Du er det rette sted for et fantastisk look.'],
      ['merhaba_2','Velkommen, tak for at betro os dit hår.'],
      ['merhaba_3','Hej, vi er her for et nyt look!'],
      ['hizmet_sor','Hvilken af vores tjenester ønsker du?'],
      ['islem_sor','Vil du have hårklipning, farvning eller pleje?'],
      ['stilist_sor','Har du en præference for en bestemt stylist?'],
      ['sac_tipi','Hvad er dit hårs længde og type?'],
      ['kimyasal','Har du tidligere fået foretaget en kemisk behandling?'],
      ['renk_sor','Hvilken farvetone tænker du på?'],
      ['referans','Har du et referencefoto?'],
      ['teknik_sor','Ønsker du balayage, ombre eller en enkelt farve?'],
      ['berber_islem','Hårklipning, barbering eller begge dele?'],
      ['sakal_sor','Ønsker du, at vi klipper eller former dit skæg?'],
      ['ustura','Ønsker du en klassisk barbering med barberkniv?'],
      ['maske','Ønsker du at tilføje en hårplejemaske?'],
      ['kas','Ønsker du at benytte vores øjenbryn-service?'],
      ['onay_1','Din aftale er modtaget, gør dig klar til at se stilfuld ud!'],
      ['onay_2','Din stylist venter på dig på det aftalte tidspunkt.'],
      ['onay_3','Din reservation er bekræftet, vi ønsker dig en god oplevelse.'],
      ['bilgi_1','Du behøver ikke at vaske dit hår før din aftale.'],
    ],
  },
  es: {
    universal: [
      ['merhaba_1','Hola, ¡bienvenido! ¿Cómo puedo ayudarle?'],
      ['merhaba_2','¡Hola! ¿Cómo puedo ayudarle hoy?'],
      ['merhaba_3','¡Buenos días! Es un placer tenerle entre nosotros.'],
      ['merhaba_4','Hola, soy su asistente digital. ¿Cómo puedo ayudarle?'],
      ['merhaba_5','¡Bienvenido! Está en el lugar correcto para hacer su reserva.'],
      ['tarih_sor','¿En qué fecha desea hacer su cita?'],
      ['saat_sor','¿Cuál es su horario preferido?'],
      ['isim_sor','¿Podría decirme su nombre y apellido?'],
      ['telefon_sor','¿Podría darme su número de teléfono?'],
      ['email_sor','¿Podría compartir su dirección de correo electrónico?'],
      ['kisi_sor','¿Para cuántas personas desea hacer la reserva?'],
      ['ozel_istek','¿Tiene alguna solicitud especial?'],
      ['ilk_ziyaret','¿Ha venido a vernos antes?'],
      ['onay_1','Su reserva ha sido creada con éxito.'],
      ['onay_2','Su cita ha sido confirmada, le esperamos.'],
      ['onay_3','¡Fantástico! Todo está en orden, hasta pronto.'],
      ['onay_bildirim','Le hemos enviado los detalles de su reserva por SMS y correo electrónico.'],
      ['teyit_sor','Para confirmar su cita, diga Sí o pulse la tecla uno.'],
      ['tekrar','¿He entendido bien la información? Déjeme repetirla una vez más.'],
      ['iptal_1','Entiendo que desea cancelar su reserva.'],
      ['iptal_2','Su reserva ha sido cancelada. Esperamos verle de nuevo.'],
      ['degisiklik_sor','¿Desea cambiar su cita?'],
      ['yeni_tarih','¿Cuál es su nueva fecha preferida?'],
      ['degisiklik_onay','Su cambio ha sido guardado.'],
      ['dolu_1','Lo siento, el horario seleccionado está ocupado. ¿Podemos probar con otro horario?'],
      ['dolu_2','Lamentablemente, no hay plazas disponibles en esta fecha.'],
      ['hata_1','Se ha producido un problema, ¿podría intentarlo de nuevo?'],
      ['anlayamadim','No he podido verificar la información que ha proporcionado, ¿podría repetirla?'],
      ['ses_yok','No le he entendido bien, ¿podría hablar un poco más alto?'],
      ['hatirlatma_1','Le llamamos por su cita de mañana, buenos días.'],
      ['hatirlatma_2','Quedan dos horas para su cita, le esperamos.'],
      ['hatirlatma_iptal','Si desea cancelar su cita, puede llamarnos.'],
      ['veda_1','Gracias, le deseamos un buen día.'],
      ['veda_2','Hasta pronto, cuídese.'],
      ['veda_3','Gracias por elegirnos.'],
      ['veda_4','Buenos días, hasta luego.'],
      ['baska_yardim','¿Puedo ayudarle en algo más?'],
      ['veda_kisa','¡Hasta luego!'],
    ],
    restoran: [
      ['merhaba_1','¡Hola, está en el lugar perfecto para una experiencia deliciosa!'],
      ['merhaba_2','¡Bienvenido! Es un placer ayudarle a reservar una mesa.'],
      ['merhaba_3','¡Hola! ¿Celebra algún día especial, o simplemente planifica una agradable comida?'],
      ['kisi_sor','¿Para cuántas personas desea reservar una mesa?'],
      ['mekan_sor','¿Prefiere interior o exterior?'],
      ['sigara_sor','¿Desea sentarse en la zona de fumadores o de no fumadores?'],
      ['ozel_gun','¿Hay algún cumpleaños o celebración especial?'],
      ['diyet','Disponemos de opciones vegetarianas y veganas en el menú, ¿desea indicarlo?'],
      ['alerji','¿Tiene alergia a algún alimento?'],
      ['cocuk','¿Desea una silla para bebé o un menú infantil?'],
      ['pencere','¿Desea una mesa junto a la ventana?'],
      ['dekor','¿Desea que preparemos decoración especial o flores?'],
      ['mutfak_bilgi','Nuestra cocina está compuesta por gastronomía turca y mediterránea.'],
      ['menu_bilgi','Para nuestro menú especial diario, visite nuestra página web.'],
      ['kahvalti','Nuestro desayuno bufé se sirve los fines de semana.'],
      ['otopark','Disponemos de servicio de aparcamiento gratuito.'],
      ['vale','Puede aprovechar nuestro servicio de aparcamiento con valet.'],
      ['onay_1','Su mesa está preparada, ¡que aproveche!'],
      ['onay_2','Su reserva ha sido recibida, le deseamos una deliciosa comida.'],
      ['onay_3','Será un placer recibirle en la mejor mesa.'],
      ['gec_kalma','Si llega tarde, llámenos por favor, guardaremos su mesa durante quince minutos.'],
    ],
    guzellik: [
      ['merhaba_1','¡Hola, ha venido al lugar perfecto para mimarse!'],
      ['merhaba_2','¡Bienvenido! Estamos aquí para una experiencia relajante.'],
      ['merhaba_3','¡Hola, hoy se toma un tiempo especial para usted, es una elección estupenda!'],
      ['hizmet_sor','¿De cuál de nuestros servicios desea beneficiarse?'],
      ['hizmet_liste','Disponemos de masaje, cuidado facial o tratamientos corporales.'],
      ['amac_sor','¿Prefiere relajación, purificación o revitalización?'],
      ['sure_sor','Determinemos la duración de su sesión: ¿cincuenta o ochenta minutos?'],
      ['cift_sor','¿Prefiere una sesión en pareja o individual?'],
      ['cilt_tipi','¿Podría informarnos sobre su tipo de piel?'],
      ['alerji','¿Tiene alguna alergia o sensibilidad?'],
      ['hamile','¿Está embarazada? Necesitamos saberlo para algunos de nuestros servicios.'],
      ['terapist_sor','¿Tiene preferencia por algún terapeuta en particular?'],
      ['aromaterapi','¿Prefiere la aromaterapia?'],
      ['sicak_tas','¿Desea añadir el masaje con piedras calientes?'],
      ['erken_gel','Le recomendamos que llegue diez minutos antes de su sesión.'],
      ['havlu','El servicio de toallas y zapatillas es gratuito.'],
      ['su','Le recomendamos beber agua, se le ofrecerá agua después de su sesión.'],
      ['onay_1','¡Su cita está lista, se sentirá muy bien!'],
      ['onay_2','Su sesión ha sido confirmada. ¡Prepárese para relajarse!'],
      ['onay_3','Le esperamos, estamos seguros de que tendrá una experiencia maravillosa.'],
    ],
    saglik: [
      ['merhaba_1','Hola, gracias por llamar a nuestra clínica.'],
      ['merhaba_2','Bienvenido, ha dado el paso correcto para su salud.'],
      ['merhaba_3','Hola, está hablando con nuestro centro de citas.'],
      ['uzman_sor','¿Para qué especialidad desea pedir cita?'],
      ['kayit_sor','¿Ha visitado nuestra clínica anteriormente?'],
      ['tc_sor','¿Podría facilitarme su número de identificación?'],
      ['sigorta_sor','¿Podría compartir su información de seguro?'],
      ['sgk_sor','¿Desea utilizar el seguro médico público o el seguro privado?'],
      ['sikayet_sor','¿Podría describir brevemente su queja?'],
      ['kronik','¿Tiene alguna enfermedad crónica o tratamiento en curso?'],
      ['ilac_sor','¿Toma algún medicamento?'],
      ['acil_sor','¿Prefiere una cita urgente o una cita normal?'],
      ['terapi_turu','¿Prefiere terapia individual, de pareja o familiar?'],
      ['online_seans','También disponemos de la posibilidad de sesiones en línea.'],
      ['gizlilik','La información de su sesión se mantiene completamente confidencial.'],
      ['ilk_seans','La primera sesión es una sesión de evaluación, su cita durará sesenta minutos.'],
      ['dis_tur','¿Desea una revisión, tratamiento o procedimiento estético?'],
      ['dis_agri','¿Tiene dolor de muelas?'],
      ['onay_1','Su cita ha sido creada, le deseamos días saludables.'],
      ['onay_2','Su médico le estará esperando a la hora acordada.'],
      ['iptal_bilgi','Para cancelar su cita, llámenos con veinticuatro horas de antelación.'],
      ['belgeler','Le pedimos que traiga su identificación y tarjeta de seguro.'],
      ['ac_karin','Debe venir en ayunas.'],
    ],
    kuafor: [
      ['merhaba_1','¡Hola! Está en el lugar correcto para un aspecto fantástico.'],
      ['merhaba_2','Bienvenido, gracias por confiarnos su cabello.'],
      ['merhaba_3','¡Hola, estamos aquí para un nuevo look!'],
      ['hizmet_sor','¿Qué servicio de los nuestros desea?'],
      ['islem_sor','¿Corte de cabello, coloración o tratamiento?'],
      ['stilist_sor','¿Tiene preferencia por algún estilista en particular?'],
      ['sac_tipi','¿Cuál es la longitud y el tipo de su cabello?'],
      ['kimyasal','¿Se ha realizado algún tratamiento químico anteriormente?'],
      ['renk_sor','¿Qué tono de color tiene en mente?'],
      ['referans','¿Tiene alguna foto de referencia?'],
      ['teknik_sor','¿Desea balayage, ombre o un color uniforme?'],
      ['berber_islem','¿Corte de cabello, afeitado o ambos?'],
      ['sakal_sor','¿Desea que le cortemos o moldemos la barba?'],
      ['ustura','¿Desea un afeitado clásico con navaja?'],
      ['maske','¿Desea añadir una mascarilla para el cabello?'],
      ['kas','¿Desea aprovechar nuestro servicio de depilación de cejas?'],
      ['onay_1','Su cita ha sido recibida, ¡prepárese para lucir elegante!'],
      ['onay_2','Su estilista le estará esperando a la hora acordada.'],
      ['onay_3','Su reserva ha sido confirmada, le deseamos una agradable experiencia.'],
      ['bilgi_1','No necesita lavarse el cabello antes de su cita.'],
    ],
  },
  ru: {
    universal: [
      ['merhaba_1','Здравствуйте, добро пожаловать! Чем могу помочь?'],
      ['merhaba_2','Здравствуйте! Чем могу помочь вам сегодня?'],
      ['merhaba_3','Добрый день! Рады видеть вас у нас.'],
      ['merhaba_4','Здравствуйте, я ваш цифровой помощник. Чем могу помочь?'],
      ['merhaba_5','Добро пожаловать! Вы обратились по адресу для бронирования.'],
      ['tarih_sor','На какую дату вы хотите записаться?'],
      ['saat_sor','Какое время вам удобно?'],
      ['isim_sor','Могу я узнать ваше имя и фамилию?'],
      ['telefon_sor','Могу я узнать ваш номер телефона?'],
      ['email_sor','Не могли бы вы поделиться адресом электронной почты?'],
      ['kisi_sor','На сколько человек вы хотите забронировать?'],
      ['ozel_istek','Есть ли у вас особые пожелания?'],
      ['ilk_ziyaret','Вы бывали у нас раньше?'],
      ['onay_1','Ваше бронирование успешно создано.'],
      ['onay_2','Ваша запись подтверждена, ждём вас.'],
      ['onay_3','Замечательно! Всё готово, до встречи.'],
      ['onay_bildirim','Мы отправили детали вашего бронирования по СМС и электронной почте.'],
      ['teyit_sor','Чтобы подтвердить запись, скажите Да или нажмите клавишу один.'],
      ['tekrar','Я правильно понял информацию? Позвольте повторить ещё раз.'],
      ['iptal_1','Понимаю, что вы хотите отменить бронирование.'],
      ['iptal_2','Ваше бронирование отменено. Надеемся увидеть вас снова.'],
      ['degisiklik_sor','Хотите изменить вашу запись?'],
      ['yeni_tarih','Какая новая дата вам подходит?'],
      ['degisiklik_onay','Ваши изменения сохранены.'],
      ['dolu_1','Извините, выбранное время занято. Можем ли мы попробовать другое время?'],
      ['dolu_2','К сожалению, на эту дату мест нет.'],
      ['hata_1','Возникла проблема, пожалуйста, попробуйте ещё раз.'],
      ['anlayamadim','Не удалось проверить введённые данные, не могли бы вы повторить?'],
      ['ses_yok','Я вас не понял, не могли бы вы говорить немного громче?'],
      ['hatirlatma_1','Мы звоним по поводу вашей записи на завтра, добрый день.'],
      ['hatirlatma_2','До вашей записи осталось два часа, ждём вас.'],
      ['hatirlatma_iptal','Если вы хотите отменить запись, вы можете позвонить нам.'],
      ['veda_1','Спасибо, желаем вам хорошего дня.'],
      ['veda_2','До свидания, берегите себя.'],
      ['veda_3','Спасибо, что выбрали нас.'],
      ['veda_4','Добрый день, до свидания.'],
      ['baska_yardim','Могу ли я помочь вам ещё с чем-нибудь?'],
      ['veda_kisa','До свидания!'],
    ],
    restoran: [
      ['merhaba_1','Здравствуйте, вы обратились по адресу для незабываемого гастрономического опыта!'],
      ['merhaba_2','Добро пожаловать! Рад помочь вам забронировать столик.'],
      ['merhaba_3','Здравствуйте! Вы отмечаете особый день или просто планируете приятный ужин?'],
      ['kisi_sor','На сколько человек вы хотите забронировать столик?'],
      ['mekan_sor','Вы предпочитаете сидеть внутри или на улице?'],
      ['sigara_sor','Вы хотите сидеть в зоне для курящих или некурящих?'],
      ['ozel_gun','Есть ли день рождения или особый повод для праздника?'],
      ['diyet','В нашем меню есть вегетарианские и веганские блюда, хотите отметить это?'],
      ['alerji','Есть ли у вас аллергия на какие-либо продукты?'],
      ['cocuk','Вам нужен детский стул или детское меню?'],
      ['pencere','Вы хотите столик у окна?'],
      ['dekor','Хотите, чтобы мы подготовили особое украшение или цветы?'],
      ['mutfak_bilgi','Наша кухня включает турецкую и средиземноморскую кухни.'],
      ['menu_bilgi','Для получения информации о нашем дневном специальном меню посетите наш сайт.'],
      ['kahvalti','Наш шведский стол для завтрака подаётся по выходным.'],
      ['otopark','У нас есть бесплатная парковка.'],
      ['vale','Вы можете воспользоваться нашей услугой парковки с водителем.'],
      ['onay_1','Ваш столик готов, приятного аппетита заранее!'],
      ['onay_2','Ваше бронирование принято, желаем вам вкусного обеда.'],
      ['onay_3','Будет удовольствием принять вас за лучшим столиком.'],
      ['gec_kalma','Если вы задерживаетесь, пожалуйста, позвоните нам, мы сохраним ваш столик на пятнадцать минут.'],
    ],
    guzellik: [
      ['merhaba_1','Здравствуйте, вы пришли по адресу, чтобы побаловать себя!'],
      ['merhaba_2','Добро пожаловать! Мы здесь для расслабляющего опыта.'],
      ['merhaba_3','Здравствуйте, сегодня вы уделяете время себе, отличный выбор!'],
      ['hizmet_sor','Какой из наших услуг вы хотите воспользоваться?'],
      ['hizmet_liste','У нас есть массаж, уход за кожей лица или уход за телом.'],
      ['amac_sor','Что предпочитаете: расслабление, очищение или восстановление?'],
      ['sure_sor','Определимся с продолжительностью сеанса: пятьдесят или восемьдесят минут?'],
      ['cift_sor','Вы предпочитаете парный или одиночный сеанс?'],
      ['cilt_tipi','Не могли бы вы рассказать нам о вашем типе кожи?'],
      ['alerji','Есть ли у вас аллергия или чувствительность?'],
      ['hamile','Вы беременны? Нам нужно знать это для некоторых наших услуг.'],
      ['terapist_sor','Есть ли у вас предпочтение по конкретному терапевту?'],
      ['aromaterapi','Предпочитаете ли вы ароматерапию?'],
      ['sicak_tas','Хотите добавить массаж горячими камнями?'],
      ['erken_gel','Рекомендуем приходить за десять минут до начала сеанса.'],
      ['havlu','Полотенца и тапочки предоставляются бесплатно.'],
      ['su','Рекомендуем пить воду, после сеанса вам предложат воду.'],
      ['onay_1','Ваша запись готова, вы будете чувствовать себя прекрасно!'],
      ['onay_2','Ваш сеанс подтверждён. Приготовьтесь к расслаблению!'],
      ['onay_3','Ждём вас, мы уверены, что вы получите прекрасные впечатления.'],
    ],
    saglik: [
      ['merhaba_1','Здравствуйте, спасибо, что позвонили в нашу клинику.'],
      ['merhaba_2','Добро пожаловать, вы сделали правильный шаг для своего здоровья.'],
      ['merhaba_3','Здравствуйте, вы говорите с нашим центром записи.'],
      ['uzman_sor','К какому специалисту вы хотите записаться?'],
      ['kayit_sor','Вы ранее обращались в нашу клинику?'],
      ['tc_sor','Можете ли вы сообщить мне свой номер удостоверения личности?'],
      ['sigorta_sor','Не могли бы вы поделиться информацией о страховке?'],
      ['sgk_sor','Вы хотите воспользоваться государственным или частным страхованием?'],
      ['sikayet_sor','Не могли бы вы кратко описать вашу жалобу?'],
      ['kronik','Есть ли у вас хроническое заболевание или текущее лечение?'],
      ['ilac_sor','Вы принимаете какие-либо лекарства?'],
      ['acil_sor','Вы предпочитаете срочную или обычную запись?'],
      ['terapi_turu','Вы предпочитаете индивидуальную, семейную или парную терапию?'],
      ['online_seans','У нас также есть возможность проведения онлайн-сеансов.'],
      ['gizlilik','Информация о вашем сеансе строго конфиденциальна.'],
      ['ilk_seans','Первый сеанс является ознакомительным, ваша запись продлится шестьдесят минут.'],
      ['dis_tur','Вы хотите плановый осмотр, лечение или эстетическую процедуру?'],
      ['dis_agri','У вас болит зуб?'],
      ['onay_1','Ваша запись создана, желаем вам здоровья.'],
      ['onay_2','Ваш врач будет ждать вас в назначенное время.'],
      ['iptal_bilgi','Для отмены записи позвоните нам за двадцать четыре часа.'],
      ['belgeler','Просим вас принести удостоверение личности и страховую карту.'],
      ['ac_karin','Вам необходимо прийти натощак.'],
    ],
    kuafor: [
      ['merhaba_1','Здравствуйте! Вы пришли по адресу для отличного образа.'],
      ['merhaba_2','Добро пожаловать, спасибо, что доверяете нам свои волосы.'],
      ['merhaba_3','Здравствуйте, мы здесь ради нового образа!'],
      ['hizmet_sor','Какую из наших услуг вы хотите?'],
      ['islem_sor','Стрижка, окрашивание или уход?'],
      ['stilist_sor','Есть ли у вас предпочтение по конкретному стилисту?'],
      ['sac_tipi','Какова длина и тип ваших волос?'],
      ['kimyasal','Вы ранее делали химическую обработку волос?'],
      ['renk_sor','Какой оттенок цвета вы рассматриваете?'],
      ['referans','Есть ли у вас фото для ориентира?'],
      ['teknik_sor','Вы хотите балаяж, омбре или однотонное окрашивание?'],
      ['berber_islem','Стрижка, бритьё или и то, и другое?'],
      ['sakal_sor','Вы хотите, чтобы мы подстригли или придали форму вашей бороде?'],
      ['ustura','Вы хотите классическое бритьё опасной бритвой?'],
      ['maske','Хотите добавить маску для волос?'],
      ['kas','Хотите воспользоваться нашей услугой коррекции бровей?'],
      ['onay_1','Ваша запись принята, готовьтесь к стильному образу!'],
      ['onay_2','Ваш стилист будет ждать вас в назначенное время.'],
      ['onay_3','Ваша запись подтверждена, желаем вам приятного опыта.'],
      ['bilgi_1','Вам не нужно мыть волосы перед записью.'],
    ],
  },
}

const MULTILANG_LOOKUP = new Map<string, { category: AudioCategory; key: string }>()
for (const [lang, categories] of Object.entries(MULTILANG_SENTENCES)) {
  for (const [cat, items] of Object.entries(categories) as [AudioCategory, Array<[string, string]>][]) {
    for (const [key, text] of items) {
      MULTILANG_LOOKUP.set(`${lang}:${normalize(text)}`, { category: cat, key })
    }
  }
}

export function findMultilangAudioFile(answer: string, lang: MultilangLang): string | null {
  const match = MULTILANG_LOOKUP.get(`${lang}:${normalize(answer)}`)
  if (!match) return null
  const p = path.join(AUDIO_DIR, lang, 'default', match.category, `${match.key}.mp3`)
  try {
    fs.accessSync(p, fs.constants.R_OK)
    return p
  } catch {
    return null
  }
}

// businessType string → audio category
export function resolveCategory(businessType: string): AudioCategory {
  const t = businessType.toLowerCase()
  if (t.includes('restoran') || t.includes('kafe') || t.includes('bar') || t.includes('yemek')) return 'restoran'
  if (t.includes('güzellik') || t.includes('guzellik') || t.includes('spa') || t.includes('masaj') || t.includes('estetik')) return 'guzellik'
  if (t.includes('sağlık') || t.includes('saglik') || t.includes('klinik') || t.includes('diş') || t.includes('dis') || t.includes('psiko') || t.includes('terapi')) return 'saglik'
  if (t.includes('kuaför') || t.includes('kuafor') || t.includes('berber') || t.includes('saç') || t.includes('sac')) return 'kuafor'
  return 'universal'
}

// Sentence map: category → [key, text][]
const SENTENCES: Record<AudioCategory, Array<[string, string]>> = {
  universal: [
    ['merhaba_1', 'Merhaba, hoş geldiniz! Size nasıl yardımcı olabilirim?'],
    ['merhaba_2', 'Merhaba! Bugün size nasıl yardımcı olabilirim?'],
    ['merhaba_3', 'İyi günler! Sizi aramızda görmekten mutluluk duyarız.'],
    ['merhaba_4', 'Merhaba, ben dijital asistanınızım. Nasıl yardımcı olabilirim?'],
    ['merhaba_5', 'Hoş geldiniz! Rezervasyon için doğru yerdesiniz.'],
    ['tarih_sor', 'Hangi tarihte randevu almak istersiniz?'],
    ['saat_sor', 'Saat tercihiniz nedir?'],
    ['isim_sor', 'Adınızı ve soyadınızı öğrenebilir miyim?'],
    ['telefon_sor', 'Telefon numaranızı alabilir miyim?'],
    ['email_sor', 'E-posta adresinizi paylaşır mısınız?'],
    ['kisi_sor', 'Kaç kişilik rezervasyon yapmak istersiniz?'],
    ['ozel_istek', 'Herhangi bir özel isteğiniz var mı?'],
    ['ilk_ziyaret', 'Daha önce bizi tercih ettiniz mi?'],
    ['onay_1', 'Rezervasyonunuz başarıyla oluşturuldu.'],
    ['onay_2', 'Randevunuz onaylandı, sizi bekliyoruz.'],
    ['onay_3', 'Harika! Her şey tamam, görüşmek üzere.'],
    ['onay_bildirim', 'Rezervasyon detaylarınızı SMS ve e-posta ile ilettik.'],
    ['teyit_sor', 'Randevunuzu onaylamak için lütfen Evet deyin veya bir tuşuna basın.'],
    ['tekrar', 'Bilgileri doğru anladım mı? Bir kez daha tekrarlayayım.'],
    ['iptal_1', 'Rezervasyonunuzu iptal etmek istediğinizi anlıyorum.'],
    ['iptal_2', 'Rezervasyonunuz iptal edildi. Tekrar görüşmek dileğiyle.'],
    ['degisiklik_sor', 'Randevunuzu değiştirmek ister misiniz?'],
    ['yeni_tarih', 'Yeni tarih tercihiniz nedir?'],
    ['degisiklik_onay', 'Değişikliğiniz kaydedildi.'],
    ['dolu_1', 'Üzgünüm, seçtiğiniz saat dolu. Başka bir saat deneyebilir miyiz?'],
    ['dolu_2', 'Maalesef bu tarihte müsait yerimiz bulunmamaktadır.'],
    ['hata_1', 'Bir sorun oluştu, lütfen tekrar dener misiniz?'],
    ['anlayamadim', 'Girdiğiniz bilgileri doğrulayamadım, tekrar söyler misiniz?'],
    ['ses_yok', 'Sizi doğru anlayamadım, biraz daha yüksek sesle söyler misiniz?'],
    ['hatirlatma_1', 'Yarınki randevunuz için sizi aradık, iyi günler.'],
    ['hatirlatma_2', 'Randevunuza iki saat kaldı, sizi bekliyoruz.'],
    ['hatirlatma_iptal', 'Randevunuzu iptal etmek isterseniz bizi arayabilirsiniz.'],
    ['veda_1', 'Teşekkür ederiz, iyi günler dileriz.'],
    ['veda_2', 'Görüşmek üzere, kendinize iyi bakın.'],
    ['veda_3', 'Bizi tercih ettiğiniz için teşekkürler.'],
    ['veda_4', 'İyi günler, hoşça kalın.'],
    ['baska_yardim', 'Başka bir konuda yardımcı olabilir miyim?'],
    ['veda_kisa', 'Görüşmek üzere!'],
    ['sayi_0', 'sıfır'], ['sayi_1', 'bir'], ['sayi_2', 'iki'], ['sayi_3', 'üç'],
    ['sayi_4', 'dört'], ['sayi_5', 'beş'], ['sayi_6', 'altı'], ['sayi_7', 'yedi'],
    ['sayi_8', 'sekiz'], ['sayi_9', 'dokuz'], ['sayi_10', 'on'], ['sayi_11', 'on bir'],
    ['sayi_12', 'on iki'], ['sayi_13', 'on üç'], ['sayi_14', 'on dört'], ['sayi_15', 'on beş'],
    ['sayi_16', 'on altı'], ['sayi_17', 'on yedi'], ['sayi_18', 'on sekiz'], ['sayi_19', 'on dokuz'],
    ['sayi_20', 'yirmi'], ['sayi_21', 'yirmi bir'], ['sayi_22', 'yirmi iki'], ['sayi_23', 'yirmi üç'],
    ['sayi_30', 'otuz'], ['sayi_45', 'kırk beş'],
    ['gun_pazartesi', 'Pazartesi'], ['gun_sali', 'Salı'], ['gun_carsamba', 'Çarşamba'],
    ['gun_persembe', 'Perşembe'], ['gun_cuma', 'Cuma'], ['gun_cumartesi', 'Cumartesi'],
    ['gun_pazar', 'Pazar'], ['gun_bugun', 'bugün'], ['gun_yarin', 'yarın'],
    ['ay_ocak', 'Ocak'], ['ay_subat', 'Şubat'], ['ay_mart', 'Mart'], ['ay_nisan', 'Nisan'],
    ['ay_mayis', 'Mayıs'], ['ay_haziran', 'Haziran'], ['ay_temmuz', 'Temmuz'],
    ['ay_agustos', 'Ağustos'], ['ay_eylul', 'Eylül'], ['ay_ekim', 'Ekim'],
    ['ay_kasim', 'Kasım'], ['ay_aralik', 'Aralık'],
    ['baglac_saat', 'saat'], ['baglac_icin', 'için'], ['baglac_kisilik', 'kişilik'],
    ['baglac_masa', 'masa'], ['baglac_randevu', 'randevu'], ['baglac_ve', 've'],
    ['baglac_tamam', 'tamam'], ['baglac_harika', 'harika'], ['baglac_tesekkur', 'teşekkürler'],
  ],
  restoran: [
    ['merhaba_1', 'Merhaba, lezzetli bir deneyim için doğru yerdesiniz!'],
    ['merhaba_2', 'Hoş geldiniz! Masa rezervasyonu için yardımcı olmaktan mutluluk duyarım.'],
    ['merhaba_3', 'Merhaba! Özel bir gün mü kutluyorsunuz, yoksa keyifli bir yemek mi planlıyorsunuz?'],
    ['kisi_sor', 'Kaç kişilik bir masa ayırtmak istersiniz?'],
    ['mekan_sor', 'İç mekan mı, dış mekan mı tercih edersiniz?'],
    ['sigara_sor', 'Sigara içilen bölümde mi, içilmeyen bölümde mi oturmak istersiniz?'],
    ['ozel_gun', 'Doğum günü veya özel bir kutlama mı var?'],
    ['diyet', 'Menümüzde vejetaryen ve vegan seçeneklerimiz mevcuttur, belirtmek ister misiniz?'],
    ['alerji', 'Alerjiniz olan bir gıda var mı?'],
    ['cocuk', 'Bebek sandalyesi veya çocuk menüsü ister misiniz?'],
    ['pencere', 'Pencere kenarı masa ister misiniz?'],
    ['dekor', 'Özel dekorasyon veya çiçek hazırlamamızı ister misiniz?'],
    ['mutfak_bilgi', 'Mutfağımız Türk ve Akdeniz mutfağından oluşmaktadır.'],
    ['menu_bilgi', 'Günlük özel menümüz için lütfen web sitemizi ziyaret edin.'],
    ['kahvalti', 'Açık büfe kahvaltımız hafta sonları sunulmaktadır.'],
    ['otopark', 'Ücretsiz otopark hizmetimiz bulunmaktadır.'],
    ['vale', 'Vale park hizmetimizden yararlanabilirsiniz.'],
    ['onay_1', 'Masanız hazırlandı, afiyet şimdiden!'],
    ['onay_2', 'Rezervasyonunuz alındı, lezzetli bir yemek dileriz.'],
    ['onay_3', 'Sizi en güzel masada ağırlamaktan mutluluk duyacağız.'],
    ['gec_kalma', 'Geç kalmanız durumunda lütfen bizi arayın, masanızı on beş dakika saklarız.'],
  ],
  guzellik: [
    ['merhaba_1', 'Merhaba, kendinizi şımartmak için doğru yere geldiniz!'],
    ['merhaba_2', 'Hoş geldiniz! Dinlendirici bir deneyim için buradayız.'],
    ['merhaba_3', 'Merhaba, bugün kendinize özel zaman ayırıyorsunuz, harika bir seçim!'],
    ['hizmet_sor', 'Hangi hizmetimizden yararlanmak istersiniz?'],
    ['hizmet_liste', 'Masaj, cilt bakımı veya vücut bakımı tercihlerimiz mevcuttur.'],
    ['amac_sor', 'Rahatlama mı, arındırma mı yoksa canlandırma mı tercih edersiniz?'],
    ['sure_sor', 'Seans sürenizi belirleyelim: elli dakika mı, seksen dakika mı?'],
    ['cift_sor', 'Çift veya tekli seans mı tercih edersiniz?'],
    ['cilt_tipi', 'Cilt tipiniz hakkında bilgi verir misiniz?'],
    ['alerji', 'Herhangi bir alerjiniz veya hassasiyetiniz var mı?'],
    ['hamile', 'Hamile misiniz? Bazı hizmetlerimiz için bilmemiz gerekiyor.'],
    ['terapist_sor', 'Belirli bir terapist tercihiniz var mı?'],
    ['aromaterapi', 'Aromaterapi tercih eder misiniz?'],
    ['sicak_tas', 'Sıcak taş masajı eklemek ister misiniz?'],
    ['erken_gel', 'Seansınızdan on dakika önce gelmenizi öneririz.'],
    ['havlu', 'Havlu ve terlik hizmetimiz ücretsizdir.'],
    ['su', 'Su içmenizi tavsiye ederiz, seansınızdan sonra su ikram edilecektir.'],
    ['onay_1', 'Randevunuz hazır, kendinizi iyi hissedeceksiniz!'],
    ['onay_2', 'Seansınız onaylandı. Gevşemeye hazır olun!'],
    ['onay_3', 'Sizi bekliyoruz, güzel bir deneyim geçireceğinizden eminiz.'],
  ],
  saglik: [
    ['merhaba_1', 'Merhaba, kliniğimizi aradığınız için teşekkür ederiz.'],
    ['merhaba_2', 'Hoş geldiniz, sağlığınız için doğru adımı attınız.'],
    ['merhaba_3', 'Merhaba, randevu merkezimiz ile görüşüyorsunuz.'],
    ['uzman_sor', 'Hangi uzmanlık alanı için randevu almak istersiniz?'],
    ['kayit_sor', 'Daha önce kliniğimize başvurdunuz mu?'],
    ['tc_sor', 'T.C. kimlik numaranızı öğrenebilir miyim?'],
    ['sigorta_sor', 'Sigorta bilgilerinizi paylaşır mısınız?'],
    ['sgk_sor', 'SGK veya özel sigorta mı kullanmak istersiniz?'],
    ['sikayet_sor', 'Şikayetinizi kısaca belirtebilir misiniz?'],
    ['kronik', 'Kronik bir hastalığınız veya süregelen bir tedaviniz var mı?'],
    ['ilac_sor', 'Kullandığınız ilaçlar var mı?'],
    ['acil_sor', 'Acil randevu mu, normal randevu mu tercih edersiniz?'],
    ['terapi_turu', 'Bireysel mi, çift terapisi mi, aile terapisi mi tercih edersiniz?'],
    ['online_seans', 'Online seans imkânımız da mevcuttur.'],
    ['gizlilik', 'Seans bilgileriniz tamamen gizli tutulmaktadır.'],
    ['ilk_seans', 'İlk seans değerlendirme seansıdır, randevunuz altmış dakika sürecektir.'],
    ['dis_tur', 'Kontrol mü, tedavi mi yoksa estetik uygulama mı istiyorsunuz?'],
    ['dis_agri', 'Diş ağrınız var mı?'],
    ['onay_1', 'Randevunuz oluşturuldu, sağlıklı günler dileriz.'],
    ['onay_2', 'Doktorunuz sizi belirlenen saatte bekleyecektir.'],
    ['iptal_bilgi', 'Randevunuzdan yirmi dört saat önce iptal için lütfen bizi arayın.'],
    ['belgeler', 'Yanınızda kimlik ve sigorta kartınızı getirmenizi rica ederiz.'],
    ['ac_karin', 'Açık karnına gelmeniz gerekmektedir.'],
  ],
  kuafor: [
    ['merhaba_1', 'Merhaba! Harika bir görünüm için doğru yerdesiniz.'],
    ['merhaba_2', 'Hoş geldiniz, saçlarınızı emanet ettiğiniz için teşekkürler.'],
    ['merhaba_3', 'Merhaba, yeni bir görünüm için buradayız!'],
    ['hizmet_sor', 'Hangi hizmetimizi almak istersiniz?'],
    ['islem_sor', 'Saç kesimi mi, renklendirme mi yoksa bakım mı?'],
    ['stilist_sor', 'Belirli bir stilist tercihiniz var mı?'],
    ['sac_tipi', 'Saçınızın uzunluğu ve tipi nedir?'],
    ['kimyasal', 'Daha önce kimyasal işlem yaptırdınız mı?'],
    ['renk_sor', 'Hangi renk tonu düşünüyorsunuz?'],
    ['referans', 'Referans fotoğrafınız var mı?'],
    ['teknik_sor', 'Balayaj mı, ombre mi, tek renk mi istiyorsunuz?'],
    ['berber_islem', 'Saç kesimi, sakal tıraşı veya ikisi birden mi?'],
    ['sakal_sor', 'Sakalınızı kesmemizi ister misiniz, şekillendirmemizi mi?'],
    ['ustura', 'Klasik ustura tıraşı ister misiniz?'],
    ['maske', 'Saç bakım maskesi eklemek ister misiniz?'],
    ['kas', 'Kaş alma hizmetimizden yararlanmak ister misiniz?'],
    ['onay_1', 'Randevunuz alındı, şık görünmeye hazır olun!'],
    ['onay_2', 'Stilistiniz sizi belirlenen saatte bekleyecektir.'],
    ['onay_3', 'Rezervasyonunuz onaylandı, güzel bir deneyim dileriz.'],
    ['bilgi_1', 'Randevunuzdan önce saçınızı yıkamanıza gerek yoktur.'],
  ],
}

function normalize(s: string): string {
  return s.toLowerCase().trim().replace(/\s+/g, ' ')
}

// text → { category, key }
const LOOKUP = new Map<string, { category: AudioCategory; key: string }>()
for (const [cat, items] of Object.entries(SENTENCES) as [AudioCategory, Array<[string, string]>][]) {
  for (const [key, text] of items) {
    LOOKUP.set(normalize(text), { category: cat, key })
  }
}

export function findAudioFile(answer: string, businessType: string, voice: AudioVoice, lang = 'tr'): string | null {
  if ((MULTILANG_LANGS as readonly string[]).includes(lang)) {
    return findMultilangAudioFile(answer, lang as MultilangLang)
  }

  const match = LOOKUP.get(normalize(answer))
  if (!match) return null

  const businessCategory = resolveCategory(businessType)

  // Try category-specific file first (same key), then the matched category, then universal
  const candidates: string[] = []

  if (match.category !== 'universal' && match.category === businessCategory) {
    candidates.push(path.join(AUDIO_DIR, match.category, voice, `${match.key}.mp3`))
  }
  if (match.category === 'universal') {
    candidates.push(path.join(AUDIO_DIR, 'universal', voice, `${match.key}.mp3`))
  }
  if (match.category !== 'universal') {
    candidates.push(path.join(AUDIO_DIR, match.category, voice, `${match.key}.mp3`))
  }

  for (const p of candidates) {
    try {
      fs.accessSync(p, fs.constants.R_OK)
      return p
    } catch {
      // continue
    }
  }
  return null
}
